# Generated by Django 3.2.5 on 2021-07-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sextosentido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='user',
            new_name='user_id',
        ),
    ]
