# Generated by Django 3.2.5 on 2021-07-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sextosentido', '0002_rename_user_consumer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
